### ISSUE TITLE
ID is persisted in SVG file

### ISSUE THREAD

**Issue by korridor** [agatanga/flags#4]
Since the ID is persisted in the SVG file the ID cannot be removed, which is necessary to use it multiple times on the same page, since IDs need to be unique.

**Comment by vovayatsyuk** [comment]
[This line](https://github.com/agatanga/flags/blob/main/src/Factory.php#L89) should remove the id.

Maybe it's a bug with a specific flag only? What flag do you use?

**Comment by korridor** [comment]
It looks like this for me, but for many countries:

<img width="1007" alt="image" src="https://github.com/agatanga/flags/assets/26689068/5ea88aed-0512-4d8b-9918-c1e4fa2f4846">

Shouldn't it be `flag-icons-` instead of `flag-icon-css-` in the line of code that you sent?

**Comment by korridor** [comment]
This SVG for example (https://raw.githubusercontent.com/agatanga/flags/main/svg/4x3/ac.svg) has `id="flag-icons-ac"`.

**Comment by vovayatsyuk** [comment]
Ah, yes! Thank you! I think it was changed a long time ago and I didn't notice it. Would you like to create a PR?
